# Generated by Django 5.1.4 on 2024-12-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='contact_us_form',
        ),
    ]
